# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:32
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcode_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grams', models.PositiveIntegerField(null=True)),
                ('filament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lulz_orders.Filament')),
                ('gcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lulz_orders.Gcode')),
            ],
        ),
        migrations.CreateModel(
            name='STL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stl_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/'), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lulz_orders.STL'),
        ),
    ]
