# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lulz_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='brand',
            field=models.CharField(choices=[('VB', 'Verbatim')], default='VB', max_length=1),
        ),
        migrations.AddField(
            model_name='filament',
            name='plastic',
            field=models.CharField(choices=[('PLA', 'PLA'), ('NGEN', 'NGEN')], default='PLA', max_length=1),
        ),
    ]
