# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lulz_orders', '0002_auto_20170614_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FilamentMaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='filament',
            name='plastic',
        ),
        migrations.AlterField(
            model_name='filament',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lulz_orders.FilamentBrand'),
        ),
        migrations.AddField(
            model_name='filament',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lulz_orders.FilamentMaterialType'),
        ),
    ]
